// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix'];
    AAlert: typeof import('@arco-design/web-vue')['Alert'];
    AAvatar: typeof import('@arco-design/web-vue')['Avatar'];
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb'];
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem'];
    AButton: typeof import('@arco-design/web-vue')['Button'];
    ACard: typeof import('@arco-design/web-vue')['Card'];
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox'];
    ACol: typeof import('@arco-design/web-vue')['Col'];
    ACollapse: typeof import('@arco-design/web-vue')['Collapse'];
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem'];
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider'];
    ADivider: typeof import('@arco-design/web-vue')['Divider'];
    ADoption: typeof import('@arco-design/web-vue')['Doption'];
    ADrawer: typeof import('@arco-design/web-vue')['Drawer'];
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown'];
    AForm: typeof import('@arco-design/web-vue')['Form'];
    AFormItem: typeof import('@arco-design/web-vue')['FormItem'];
    AGrid: typeof import('@arco-design/web-vue')['Grid'];
    AGridItem: typeof import('@arco-design/web-vue')['GridItem'];
    AImage: typeof import('@arco-design/web-vue')['Image'];
    AInput: typeof import('@arco-design/web-vue')['Input'];
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber'];
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword'];
    ALayout: typeof import('@arco-design/web-vue')['Layout'];
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent'];
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter'];
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider'];
    ALink: typeof import('@arco-design/web-vue')['Link'];
    AMenu: typeof import('@arco-design/web-vue')['Menu'];
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem'];
    AModal: typeof import('@arco-design/web-vue')['Modal'];
    AOption: typeof import('@arco-design/web-vue')['Option'];
    APagination: typeof import('@arco-design/web-vue')['Pagination'];
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm'];
    AResult: typeof import('@arco-design/web-vue')['Result'];
    ASelect: typeof import('@arco-design/web-vue')['Select'];
    ASpace: typeof import('@arco-design/web-vue')['Space'];
    ASpin: typeof import('@arco-design/web-vue')['Spin'];
    AStatistic: typeof import('@arco-design/web-vue')['Statistic'];
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu'];
    ASwitch: typeof import('@arco-design/web-vue')['Switch'];
    ATable: typeof import('@arco-design/web-vue')['Table'];
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn'];
    ATag: typeof import('@arco-design/web-vue')['Tag'];
    ATextarea: typeof import('@arco-design/web-vue')['Textarea'];
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip'];
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText'];
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
